// Generated by CoffeeScript 1.7.1
var console, debug, noop;

noop = function() {};

console = WIN["console"];

debug = WIN["debug"];

if (!IsDebug) {
  if (debug) {
    if (typeof debug.guai === "function") {
      debug.guai();
    }
  }
  console = debug = {
    log: noop,
    debug: noop,
    error: noop,
    warn: noop
  };
}
