// Generated by CoffeeScript 1.7.1
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

module.exports = function(grunt) {
  var config, getDoccoFiles;
  config = grunt.config.get("config");
  grunt.registerTask("doc", ["docco"]);
  grunt.registerTask("docs", ["doc"]);
  getDoccoFiles = function() {
    var files, ret;
    files = [];
    ret = [];
    grunt.file.recurse("" + config.app + "/scripts", function(abspath, rootdir, subdir, filename) {
      if (!("" + subdir).match(/^\.tmp|docs/)) {
        return files.push(abspath);
      }
    });
    files.forEach(function(file, index) {
      var coffeeFile;
      if (file.match(/\.js$/)) {
        coffeeFile = file.replace(/\.js$/, ".coffee");
        if (__indexOf.call(files, coffeeFile) >= 0) {
          return ret.push(coffeeFile);
        } else {
          return ret.push(file);
        }
      }
    });
    return ret;
  };
  return {
    docco: {
      script: {
        src: getDoccoFiles(),
        options: {
          output: '<%= config.doc %>'
        }
      }
    },
    connect: {
      docs: {
        options: {
          base: {
            path: '<%= config.doc %>',
            options: {
              index: "app.html"
            }
          },
          livereload: false
        }
      }
    }
  };
};
