// Generated by CoffeeScript 1.7.1
var CLICK, DOC, HIS, IsAndroid, IsBaiduBox, IsBaiduBrowser, IsChrome, IsDebug, IsHasDeviceMotion, IsIOS, IsIPad, IsIPhone, IsTouch, IsUC, IsWeixin, IsXiaoMi, LOC, REFERER, UA, WIN;

WIN = window;

DOC = document;

LOC = WIN["location"];

REFERER = DOC["referrer"];

HIS = WIN.history;

UA = WIN.navigator.userAgent;

IsTouch = "ontouchend" in WIN;

IsHasDeviceMotion = "ondevicemotion" in WIN;

IsAndroid = /Android|HTC/i.test(UA) || /Linux/i.test(WIN.navigator.platform + '');

IsIPad = !IsAndroid && /iPad/i.test(UA);

IsIPhone = !IsAndroid && /iPod|iPhone/i.test(UA);

IsIOS = IsIPad || IsIPhone;

IsXiaoMi = IsAndroid && /mi\s+/i.test(UA);

IsUC = /UCBrowser/i.test(UA);

IsWeixin = /MicroMessenger/i.test(UA);

IsBaiduBrowser = /baidubrowser/i.test(UA);

IsChrome = WIN["chrome"];

IsBaiduBox = /baiduboxapp/i.test(UA);

CLICK = "click";

IsDebug = true;
